FROM ocaml/opam2:debian-unstable-opam
RUN sudo apt-get update
WORKDIR opam-repository
RUN git checkout 632bc2eed
RUN git pull origin 2.0.0
RUN opam admin cache
RUN echo 'wrap-build-commands: []' >> ~/.opamrc
RUN echo 'wrap-install-commands: []' >> ~/.opamrc
RUN echo 'wrap-remove-commands: []' >> ~/.opamrc
RUN opam init -yac 4.07.0+beta2+flambda .
RUN echo 'archive-mirrors: ["file:///home/opam/opam-repository/cache"]' >> /home/opam/.opam/config
RUN opam install -y opam-depext
RUN git clone git://github.com/kit-ty-kate/lib-findlib.git
RUN git -C lib-findlib checkout test-407
RUN opam pin add -yn ocamlfind lib-findlib
ENV OCAMLPARAM Oclassic=1,_
CMD opam list --installable --available --short --all-versions
