FROM ocaml/opam2:debian-unstable-ocaml-4.05.0
RUN sudo apt-get update
RUN git checkout 632bc2eed
RUN git pull origin 2.0.0
RUN opam update
RUN opam admin cache
RUN echo 'archive-mirrors: ["file:///home/opam/opam-repository/cache"]' >> /home/opam/.opam/config
RUN opam switch create -y 4.06.1
RUN opam install -y opam-depext
RUN git clone git://github.com/kit-ty-kate/lib-findlib.git
RUN git -C lib-findlib checkout test-407
RUN opam pin add -yn ocamlfind lib-findlib
CMD opam list --installable --available --short --all-versions
