FROM ocaml/opam2:debian-unstable-opam
RUN sudo apt-get update
WORKDIR opam-repository
RUN git checkout 632bc2eed
RUN git pull origin 2.0.0
RUN opam admin cache
RUN echo 'wrap-build-commands: []' >> ~/.opamrc
RUN echo 'wrap-install-commands: []' >> ~/.opamrc
RUN echo 'wrap-remove-commands: []' >> ~/.opamrc
RUN opam init -yac 4.07.0+beta2+flambda .
RUN echo 'archive-mirrors: ["file:///home/opam/opam-repository/cache"]' >> /home/opam/.opam/config
RUN opam install -y opam-depext
ENV OCAMLPARAM Oclassic=1,_
CMD opam list --installable --available --short --all-versions
